### ISSUE TITLE
Deprecate abusehelper.core.archivebot

### ISSUE THREAD

**Issue by mseppanen** [abusesa/abusehelper#23]
As part of effort to clean up `abusehelper.core`, we should deprecate old `abusehelper.core.archivebot`. If it still used widely we could move it to the community repository or if not, then just delete it.

Preferred way to save archive of channel is to use new JSON archivebot at `abusehelper.bots.archivebot.archivebot`. New bot produces compressed JSON output and rotates archives daily.

**Comment by ghost** [comment]
Agreeing with completely removing the archivebot from the abusehelper core in the upcoming major revision. It would also be important to notify the community in the Jabber channel if this kind of change would be done.
