### ISSUE TITLE
abusehelper.bots.archivebot.csvarchivebot depends on deprecated abusehelper.core.archivebot

### ISSUE THREAD

**Issue by oherrala** [abusesa/abusehelper#32]
This issue blocks pull request #24.

`abusehelper.bots.archivebot.csvarchivebot` should be either deprecated or changed to use for example `abusehelper.bots.archivebot` instead.

**Comment by ghost** [comment]
`abusehelper.bots.archivebot` does not really have extension points for that (like the old `abusehelper.core.archivebot` did).
