### ISSUE TITLE
bots version

### ISSUE THREAD

**Issue by ics** [abusesa/abusehelper#38]
Premise: `INFO Starting service 'historyexpert' version unknown`

It would be nice if [version.py](https://github.com/abusesa/abusehelper/blob/master/abusehelper/core/version.py) would be updated to use the git commit hash. Ideally this should allow custom bots (I'm thinking ahcommunity package) to use this somehow. In ahcommunity we sometimes use a module level dunder, `__version__` to identify bots. An idea will be to have the parent (`abusehelper.core.bot.Bot`) read it.
This will help identifying bot's version with a quick look in logs.

**Comment by oherrala** [comment]
Hi @ics, commit 2578211b189fb73edba7410f024765f515e6e5b7 changed version information to be found from `abusehelper.__version__`. How does this look?

```
>>> import abusehelper
>>> abusehelper.__version__
'4.1.0'
```

**Comment by ics** [comment]
Looks good! 
Thank you.

**Comment by oherrala** [comment]
@ics thanks. Closing issue.
