### ISSUE TITLE
incremental relaunching strategy

### ISSUE THREAD

**Issue by ics** [abusesa/abusehelper#41]
The StartupBot implements a strategy() method which delays bot relaunching. It would be nice if the delay would increment with each relaunch (when return code is not 0) to avoid hammering servers and filing up logs.
Example scenario: 
- bot exists with status other than 0;
- first relaunch delay is 15 seconds;
- bot exists again with a non-zero status;
- relaunch delay is incremented 30 seconds;
- non-zero exist;
- relaunch delay 60 seconds;
- ...

@jviide-work suggests to have a maximum delay so we don't grow impatient while waiting for bots to start.

**Comment by evilon** [comment]
- if the delay gets to grow huge, it may be hard to detect there is an issue. Maybe max... something like 10 minutes?
