### ISSUE TITLE
Tracking issue: Convert default URLS from HTTP -> HTTPS where possible

### ISSUE THREAD

**Issue by oherrala** [abusesa/abusehelper#70]
Many bots fetch data from sources via HTTP. Convert these into HTTPS where possible.

This is tracking issue to collect all pull requests modifying bots. One pull request per bot.

**Comment by oherrala** [comment]
Pull requests #71, #72, #73, #74 and #75 are merged together in branch [`test-https-for-bots`](https://github.com/abusesa/abusehelper/tree/test-https-for-bots) for easier testing. However, this branch should not be merged into master but merge the individual bot branches as they are tested and verified to work.

**Comment by mseppanen** [comment]
All tested and merged.

**Comment by mseppanen** [comment]
There was more to fix.

**Comment by oherrala** [comment]
Fix merged.
