### ISSUE TITLE
Add Possibility to Filter Events Older than X

### ISSUE THREAD

**Issue by larihuttunen** [abusesa/abusehelper#78]
It was proposed that we add an option for source bots, which end up parsing the same source file over and over, where:
- you could define a threshold value (in seconds for example).
- it would imply that events with a "source time" older than X would not get sent into the pipeline
- it would prevent the old events being resent in case there is a change in the feed data format for example and the state file does not "catch" the old events.

The following bots at least would benefit from this option:
- [x] abusehelper.bots.openbl.openblbot
- [x] abusehelper.bots.phishtank.phishtankbot

**Comment by ghost** [comment]
I'll add this to FeedBot so most of the bots implement this.

**Comment by ghost** [comment]
Fixed in debd818
