### ISSUE TITLE
Add docs/Ontology.md for collaborating on the harmonization ontology

### ISSUE THREAD

**Issue by ghost** [abusesa/abusehelper#9]
Add `docs/Ontology.md` for collaborating on the data harmonization ontology. Or `docs/Harmonization.md`, or whatever is deemed best.

**Comment by larihuttunen** [comment]
I will start the work converting the current wiki markup into markdown. The actual improvement will be done through a WIP pull request as suggested by @jviide-work.

**Comment by ghost** [comment]
Reopening the issue. Close when #10 has been finished and merged.

**Comment by ghost** [comment]
Closing again, #10 has now been finished and merged :)
